import { useLayoutEffect, useState } from "react";
import { createPortal } from "react-dom";

interface Props {
  children: React.ReactNode;
  wrapperId?: string;
}

const Portal: React.FC<Props> = ({
  children,
  wrapperId = "portal-wrapper",
}) => {
  const [wrapperElement, setWrapperElement] = useState<HTMLElement | null>(
    null
  );

  useLayoutEffect(() => {
    let element = document.getElementById(wrapperId);
    let isAutoGenerated = false;

    if (!element) {
      isAutoGenerated = true;
      const wrapper: HTMLElement = document.createElement("div");
      wrapper.setAttribute("id", wrapperId);
      element = document.body.appendChild(wrapper);
    }

    setWrapperElement(element);
    return () => {
      if (isAutoGenerated && element) {
        document.body.removeChild(element);
      }
    };
  }, [wrapperId]);

  if (!wrapperElement) {
    return <>{null}</>;
  }

  return createPortal(children, wrapperElement);
};

export default Portal;
